version: 2.1

jobs:
  backend:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/backend/webex

    steps:
      - checkout
      - run:
          name: "Gradle Build"
          command: "gradle init build"

      - run:
          name: "test"
          command: "gradle test"

  frontend:
    docker:
      - image: cimg/node:19.8.1

    working_directory: ~/frontend

    steps:
      - checkout
      - run:
          name: "test"
          command: "ls -al"

      - run:
          name: "Run Frontend Tests (?)"
          command: "cd frontend && npm i && npm run build"

      - run:
          name: "test"
          command: "npm test"
