version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  - gradle/test
    # docker:
    #   - image: cimg/base:stable

    # steps:
    #   - checkout
    #   - run:
    #       name: "Check Backend Build"
    #       command: "sudo apt-get update && sudo apt-get install gradle && cd backend/webex && gradle build"
    #   - run:
    #       name: "Run Backend Tests (?)"
    #       command: "echo Hello World"

  frontend:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Run Frontend Tests (?)"
          command: "echo Hello, World!"

workflows:
  project-workflow:
    jobs:
      - backend
      - frontend
