version: 2.1

jobs:
  backend:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/backend/webex

    steps:
      - checkout
      - run:
          name: "Gradle Build"
          command: "gradle init build"

  frontend:
    docker:
      - image: cimg/node:19.8.1

    working_directory: ~/frontend

    steps:
      - checkout
      - run:
          name: "Run Frontend Tests (?)"
          command: "npm i && npm run start"

workflows:
  project-workflow:
    jobs:
      - backend
      - frontend
