version: 2.1

jobs:
  backend:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run:
          name: "Working Directory"
          command: "cd backend/webex"
      - run:
          name: "Gradle Dependency Install"
          command: "gradle dependencies"
      - run:
          name: "Run Build"
          command: "gradle build"
      - run:
          name: "Run Tests (?)"
          command: "echo tests"

  frontend:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Run Frontend Tests (?)"
          command: "echo Hello, World!"

workflows:
  project-workflow:
    jobs:
      - backend
      - frontend
