version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  backend:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - run:
          name: "Check Backend Build"
          command: "cd backend/webex && ./gradlew build"
      - run:
          name: "Run Backend Tests (?)"
          command: "echo Hello World"
  frontend:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Run Frontend Tests (?)"
          command: "echo Hello, World!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - say-hello-again
