version: 2.1

jobs:
  - gradle/test
    docker:
      - image: cimg/openjdk:8-jdk
    working_directory: ~/SWENG-22-CISCO/backend/webex
    steps:
      - checkout
      - run:
          name: "Gradle Dependency Install"
          command: "gradle dependencies"
      - run:
          name: "Run Build"
          command: "gradle build"
      - run:
          name: "Run Tests (?)"
          command: "echo tests"

  frontend:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Run Frontend Tests (?)"
          command: "echo Hello, World!"

workflows:
  project-workflow:
    jobs:
      - backend
      - frontend
